### ISSUE TITLE
Master crash: Too many pq connections

### ISSUE THREAD

**Issue by janisstreib** [KIT-MAMID/mamid#56]
ERRO[5810] could not find initiator for replica set `test`  error=pq: remaining connection slots are reserved for non-replication superuser connections module=deployer
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x6f38e8]

goroutine 4563 [running]:
panic(0x898620, 0xc820012110)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
database/sql.(*Tx).Rollback(0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/database/sql/sql.go:1263 +0x28
github.com/KIT-MAMID/mamid/vendor/github.com/jinzhu/gorm.(*DB).Rollback(0xc82097ba40, 0x9adbe0)
	/home/janis/gospace/src/github.com/KIT-MAMID/mamid/vendor/github.com/jinzhu/gorm/main.go:448 +0x8d
github.com/KIT-MAMID/mamid/master.(*Deployer).handleReplicaSetInitiationStatus(0xc8204444c0, 0x0, 0x2, 0xc8209a92d8, 0x4, 0x0, 0x15f91, 0xc8209a9300, 0x4, 0x0, ...)
	/home/janis/gospace/src/github.com/KIT-MAMID/mamid/master/deployer.go:87 +0x2cd
created by github.com/KIT-MAMID/mamid/master.(*Deployer).Run
	/home/janis/gospace/src/github.com/KIT-MAMID/mamid/master/deployer.go:29 +0x1ee
exit status 2

**Comment by janisstreib** [comment]
Was a missing rollback. Fixed by @antonxy  in 0cc1bbd
